---
abstract: 'a module that does something-or-other'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: MooseX::DeclareX::Keyword::interface
name: MooseX-DeclareX-Keyword-interface
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  MooseX::DeclareX: 0.002
  MooseX::Interface: 0.002
  perl: 5.005
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooseX-DeclareX-Keyword-interface
  homepage: https://metacpan.org/release/MooseX-DeclareX-Keyword-interface
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-moosex-declarex-keyword-interface
version: 0.001
